// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCantWw-qYDWn881fWPyDB_B3xODYmdT6A',
    appId: '1:772151560554:web:d08a5e09e99c3e77bfbd13',
    messagingSenderId: '772151560554',
    projectId: 'wordmagic-d94fb',
    authDomain: 'wordmagic-d94fb.firebaseapp.com',
    storageBucket: 'wordmagic-d94fb.appspot.com',
    measurementId: 'G-XFRK2M6BRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-su9uGezCpYRfx-B04NnPp9erKmLciA',
    appId: '1:772151560554:android:d6b5b9650da6ae61bfbd13',
    messagingSenderId: '772151560554',
    projectId: 'wordmagic-d94fb',
    storageBucket: 'wordmagic-d94fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBBrJMEMM2oQfMt4Gv3Ei2hif6H_L6Uik',
    appId: '1:772151560554:ios:7fc4905ccf5d3d80bfbd13',
    messagingSenderId: '772151560554',
    projectId: 'wordmagic-d94fb',
    storageBucket: 'wordmagic-d94fb.appspot.com',
    iosBundleId: 'com.example.wordMagic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBBrJMEMM2oQfMt4Gv3Ei2hif6H_L6Uik',
    appId: '1:772151560554:ios:3ecf698f7ddc4866bfbd13',
    messagingSenderId: '772151560554',
    projectId: 'wordmagic-d94fb',
    storageBucket: 'wordmagic-d94fb.appspot.com',
    iosBundleId: 'com.example.wordMagic.RunnerTests',
  );
}
